### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by Ryuji-Ichikawa** [Ryuji-Ichikawa/furima-35547#11]
#URL
https://furima-35547.herokuapp.com/
Basic認証のID: ryuji
パスワード: 5547
出品者用のメールアドレス:  taro@taro
パスワード: a11111
購入者用のメールアドレス: tom@tom
パスワード: a11111

**Comment by takumi0530** [comment]
@Ryuji-Ichikawa さん、ご提出ありがとうございます‼︎
問題なく正常に動作することが確認できました！　LGTMです✨　
おめでとうございます🎉
着実に技術力が身につき、実用的なアプリになってきてますね（^^）
これからもスタッフ一同応援しております🍀

**※確認したのは必須機能のみです。追加実装した機能については確認しておりません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるか、再度ご自身でご確認をお願い致します。**
![最終課題終了_おめでとう画像2](https://user-images.githubusercontent.com/76197191/118424052-5bec5f80-b701-11eb-80f2-02f9c3fa2494.png)
